### ISSUE TITLE
long words wrap

### ISSUE THREAD

**Issue by ewansheldon** [codurance/Retropolis-FE#38]
<img width="995" alt="Screenshot 2020-05-29 at 17 20 55" src="https://user-images.githubusercontent.com/20175637/83281972-d3636f00-a1d0-11ea-926f-16901ce81b87.png">

**Comment by TomSpencerLondon** [comment]
Should be fixed here:
https://github.com/codurance/Retropolis-FE/pull/46

**Comment by apavlidi** [comment]
Resolved on #46
